# Generated by Django 5.2.5 on 2025-08-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_first_name_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
